branches:
  only:
    - source
language: ruby
rvm:
  - 1.9.3
before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - git config --global user.name "Anthony Mastrean"
  - git config --global user.email "anthony.mastrean@gmail.com"
  - bundle exec rake setup_github_pages[$REPO_URL]
script:
  - bundle exec rake generate deploy
env:
  global:
    - GH_REPO="AnthonyMastrean/anthonymastrean.github.com"
    - secure: "FlZwq7qRnAp8SHgfgAKB1btNljx0extW+8/ekXVjCvjzPanOr5lBRMu0T1qWgqPrBvjyyM/xZfNoemyjbwCdjNws7xfD/El8jlIK107SVO9eNLKrie3QQUV3bY+heJ72tjdyHND5ansXWoPWH9s9+mMephEYPHWwo7GuRdccMlM="
