sudo: false

branches:
  only:
    - source

language: ruby

rvm:
  - 2.2.0

cache: bundler

before_script:
  - export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
  - git config --global user.name "Anthony Mastrean"
  - git config --global user.email "anthony.mastrean@gmail.com"

script:
  - bundle exec jekyll build

env:
  global:
    - GH_REPO="AnthonyMastrean/anthonymastrean.github.com"
    - secure: "FlZwq7qRnAp8SHgfgAKB1btNljx0extW+8/ekXVjCvjzPanOr5lBRMu0T1qWgqPrBvjyyM/xZfNoemyjbwCdjNws7xfD/El8jlIK107SVO9eNLKrie3QQUV3bY+heJ72tjdyHND5ansXWoPWH9s9+mMephEYPHWwo7GuRdccMlM="
