branches:
  only:
    - source
language: ruby
rvm:
  - 1.9.3
before_script:
  # Set the git config stuff, so Git stops yelling at us
  - git config --global user.name "Anthony Mastrean (via Travis-CI)"
  - git config --global user.email "anthony.mastrean@gmail.com"
  # Set read-write git origin
  - git remote set-url origin $REPO.git
  # Unpack ssh key for git
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set deployment target to github pages
  - rake setup_github_pages[$REPO]
  # Reset the 'url' to the custom domain in '_config.yml'
  - git checkout -- _config.yml
script:
  - rake generate
after_script:
  - rake deploy
env:
  global:
    # Repo read-write address
    - REPO="git@github.com:AnthonyMastrean/anthonymastrean.github.com.git"
    # SSH key. Encoded. See https://gist.github.com/4631240
    - secure: "o1RYE+ROB6lDM+jtyEwzR6EcK+h2bAf7o+4VZ/Yf+b3muwueAjVfniv59Fux3LKp3T3c0Rpi4FBY5v8CukohJUMFEgvxjUw5WPBCXiq+ZctkhYhg75Uh17m1mfbp/zYdvLqx1S5Ir/jxGAz0YsXhXUsSWltFKeh8sD/fJ42zba0="
	  - secure: "juoyJQJC62cPMQEquKLl6Dt7pM3WdXko7ZBPeieVGz5d0umDN6iTWPZjb5oJxR268i/2twEn8RpBpxjKjE4OybQmY8683qcHg9S9Z2AhPu1EGCfOZ/txKhLDfafx5hO5gJ9THRSZv1duce+8yPL5gfDmu7wjPakeRZv0HvTYEyM="
	  - secure: "H4YjyOGU77Z55RX6JYRTqqWf7zNuokwdqjLDy5L3hkhjKvJIdn7/ZN+TBimWL3lM60hRNYcXETPNAfEmIKYw1rZRxeshurxnW9IKrCNn9J2MrmMhWOLQ79pwBWXKwQVJdy/7Ay1I7SclfZ6aHbUW7vwLWeCoEdqB1uVlbOqj5T8="
	  - secure: "Sanh85+TnHZBB3DhWxZyfxcWVFkmFKJFwkNmWYliZ4Qh2l2FO1x6OF01duvh0TAeM/euXzX+rJjOMCAkt+TsYzgFFvptD3t5M07Xs6N2iGOoi9omIb4msEfJKzZW8b/OwWBOndBEPuuq66RijndAEjB3lHQ62NUAuWFtmCMkuVk="
	  - secure: "R8MXNymlIUZByc/U60yQc0nRo5AHFCth8xQIGqPr2NSpyYJKLYW2woB9s5UpTJhFtmHxsRDjFcjQA0HHqKl0BeD5/8hrJKKM8cx8ArkGz7ZttVGS7MUpLN/+AsSX2jfVS3k5MEhNU/0B9yEU8m2IpAaAfT581SNuBMjXhCnB14Q="
	  - secure: "nUtuWSrozHzkPbOaZ+2xpmJOyTXmFkF4OC9T/vNM8pQZbUOIXAwTF2NQ1IRNFu7okQmRNpk/PjkD30sHZ91hNRpRyvy7Vps7uSe0gc6e7cqx37wHaIYqdtbj+i0hnFrAj6MbfFXEOMZuxjlJsvWBc2sZ9gNPRQHKraTZZnLH3VY="
	  - secure: "XQLnY+uiMZuNWG41qbOacIyaXJUESdlVQBzZKXq97RMxv+bttrTdbTIw4pslPLVlGFALtBMMMvFcZ9VRQyHecuFyiYe/L3uojr0ajgvctKlXsZvUQZLtSJ7t9RqZhIU/iMIY61jsNDUC4pF0Ydl2JeDS3gbjZzyOc2VCtbL8G1w="
	  - secure: "q9lAhPQnJsrIchKKBlmY9AZ5XviLOOwae4kJk2VW8mnVxcYumg+88CiN3p6F/Losrd956bVAOV3+b1gRLFT2Ro5W1cbrwid642ARjWRvUM5hF9DS9Rr49tjEOrBPhGRKlvB9RV8AupJvXyQ73r0xIGTFwn4wug4pj0TRwfQL488="
	  - secure: "dFDt4jKEbTSHa59TGM6JucoA+hwf3BbkKKAZEu3KX+2jGMntWmYlSaD1lBYenQCw4Dz36uqdBi22XfuaS5aQ2gwwpz3LwupNN4J1uUPwT/yRIH4VNC99FChL3Za8YfesEesZlVpgsQ/gXUW7y1mxPPkv6+JV/CYqyKwcwc4QjK4="
	  - secure: "OAAbcSQU/rrGMIZrV7W87d4B2SKzjbFOU7hzUX9fzCaRVHNoR9ABv1FVk+ZdXfsZK4+c5Z9tgFgvb3zuMizGAKyAlDmLGv3HvXSy6inaa8ukzDUiLEagWnMq9oekW+34h4CwyLJq7rOlgyscKZK9WYECp88uCN+S4Y6sVdGx714="
	  - secure: "ebfmGIXnlBhAG6NfsI4JXf7ZzUNT/xZ7qHV/UBeMiB4osTkpEKe0/AQz8x6Hfg3iIxXg/7cs2Z+yevA7/9vVYYHgjoM/9y21ULL8PVYZ4i1TyD8xBbGGzB+lEsE/J5etg+/deMXZaWsmFpSWZCwcK3LX0RFKYMeffnZU+MuDXL0="
	  - secure: "BXIE9EyouLkzC7gjvNLlFKsAEsKvErGP47g6Ld+KurPl4cy+1vUpQQB+cwf68Tt6Xiui9WKL/BSfTgnPB5AbECkn3okqU6WWf4YkMZ9iSR/RtDZkzCfAxwGZi5IcFqvAR4fLkpHWQVi9Pusx563MzYHlMJ3Z4pvy2kYx/ILYwOs="
	  - secure: "X4rk0vSgOU7sdT4kKuLVaXCn8fE+S1t6IuAFmHB7/aQwz7XVgJMcCSy/jxBAHl7YGCHKbu1EZ9lu72OJKdtL1WPeIo3yY1palcbWosCJ07A3Oht6aGb6CIo+eIR32Dt1deqQb/ZOQ/dJGcbC5CzMXstW4qXZ7trkNZjDHtiwAe8="
	  - secure: "wGdCIuU9CpJOyYD4lrEWXIhkPw4yuFGkQuzJ+hkOW/FfOA5p40910lrRQHNlhFg79tbf+7YB9mjF8tQIWNGa0hoBLhf7G3QEDf0/ZFp/43iARN+YSMD6+Gp3RngdoSCKyxKKZfkwAMV+aCi5Wp8WOY8mdpzbtr48Izhe5sJw8nw="
	  - secure: "oAVz7HQiTfvBZxtlaQctEVU5aOnUBkkO2cNj0wR3CW5uoZfl0tPN4nMer0iqQmqIqIp/LKA5dKkpetbCehv0PH2DAUEM3cjLYFz6FkG80ff2UtL3cihTibbEA90sWOizs30N5XCst9wGtAoQRt8d1CbxuOA5ie6UGV60VC1UPEI="
	  - secure: "pVM5K3mhXD4UHOKZ8ECaXydGYVjNVQmIE6b7ofkelPgraSzhF0RgSntcv21UN9MP/J2j0bUBO95RM8k/sDGdvvMGJLhyLg973UTPOa4B/PhwRvxDQzrOSRfyVXTdJbIIIdu3+VfncZFJZwgAvr9RSQPENv59WzQvkGqmzE1zoSc="
	  - secure: "CT9Hw4DWjzskiH/jiXGgaj8KM3Pok5CRpyfx9fnc8SYsRp/KiTYz+GL9nrjH1AGR3BVyj6n0v+vA/74+PYWxeLhzBDrIeYuNAnKM3fJsdiDUk97aQe22nDV6tpyyaAzXIa41LaCEZj+3FZZLWV6ZJlr3SNeJMDoPBHM2r1z0FnA="
	  - secure: "hgojfF7fvGWouiO4HPqPjrhs9RyF/61M7fpQjZEUZ3drwQyFUWBfqt471Ve4Ofc44PH07YBWRNMk6Jwbzt9AO7dInde6Syi4whuEpARrUC5fZF+9wLmMcYCD9YU41zWbOSBtifG7o8t1R11jagnwgXQuctnLea3rFLOX4r/xpxE="
	  - secure: "ZsEejItPedHHgBkTwWVupJhb2oNo4aGfDeCHHNAFvZif/GLb//7U3xtnTFJwMTGgrGS+oI43WjIq2PIuhZjmoM3tfb/GtBCYYHGtppM+qzXJeSr8HtenERbj7qLa/x1jgL6GRizrYtEFpYJaz7j1a4gjzHnQoRKoR7PcosQJP2M="
	  - secure: "DgGKZkUEc03iCwxA1oXIPHZjo7426FDB5beHkpVACze6/Def3prCRogUMDAjEWO9/EO26CI927i5JXTgGV9aitLKMTVBQnhdRBnK/jHLLmUtQe3jDbpP4CvZpNIneMz7cmamIvQW4kyG7lomFv0FOmmuE6inhlB2ZAYCe0ostpg="
	  - secure: "ZpvZAl4zuTGPUMjV6ggrsU1jIo6t2pwr0+ZVyCIgk9SC31WOf1wPzlXNvfi1YwSzy1ZCESn9e2s2YtF2n9onmzrH9vk8cavUEroJKZf4qmhwgF8v8/t1qu+kXuKaBREHYynpDFlf2E1ibYc7YNc2ElHyt3bDsz5lULV2Xo2O1Ps="
	  - secure: "oNIJNqyPruadJpbceds/qCrjXWHpaV+CwNatd2g3Nx5eUkH3d4AbqyLe+WkH1JmCSQEkDoMVFwprrJ1zgf2JwVmVMeTJ8fWgONQ+kcjHi7H3hLAuMmRjBVucH3uVYsjJDTdI5T4nSIbQdGv033eE6fyy+/6OiN+FnpX4Ohzcs6Q="
	  - secure: "Polx2dikfpZCm7VSg1B+zXdnWfa/Lg6qy/rXcGUkXz0wjn69ph3o1ogj2x30nP0CBkfxqHPTR5VzdvMRFSHcNFl2mivK5XPGePn9KMymXbEjkzZ+e8KgqQeksleXedY3f/C9ZDJXIjGh6RRAB+DAY8BRkJgjW42aurG2dUDNs5c="
