# Site settings
title: "Anthony Mastrean"
email: "anthony.mastrean@gmail.com"
description: ""
baseurl: ""
url: "https://anthonymastrean.com"
permalink: "/blog/:title/"

# Build settings
markdown: kramdown
theme: minima
plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
 
# Theme
minima:
  date_format: "%b %-d, %Y"

# Social
rss: rss
twitter_username: anthonymastrean
github_username: anthonymastrean
stackoverflow_userid: 3619

# Paginate
paginate: 7
paginate_path: "/blog/page/:num/"
