# Site settings
title: "Anthony Mastrean"
email: "anthony.mastrean@gmail.com"
description: ""
baseurl: ""
url: "anthonymastrean.com"
permalink: "/blog/:title/"

# Theme
minima:
  date_format: "%b %-d, %Y"

# Social
rss: rss
twitter_username: anthonymastrean
github_username: anthonymastrean
stackoverflow_userid: 3619

# Build settings
markdown: kramdown
theme: minima

# Plugins
gems: ['jekyll-paginate']

# Paginate
paginate: 7
paginate_path: "/blog/page/:num/"
